nameOverride: ""
fullnameOverride: "taskflow"

backend:
  replicaCount: 1
  image:
    repository: gto310/taskflow-backend
    tag: v1.0.0
    pullPolicy: IfNotPresent 
  service:
    type: ClusterIP
    port: 8000
  resources: 
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    LOG_LEVEL: "INFO"

frontend:
  replicaCount: 1
  image:
    repository: gto310/taskflow-frontend
    tag: v1.0.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi


# Redis
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  fullnameOverride: "taskflow-redis"

# PostgreSQL
postgresql:
  enabled: true
  auth:
    username: "taskflow"
    password: "taskflowDatabase"
    database: "taskflow"
  fullnameOverride: "taskflow-postgresql"
  
  primary:
    persistence:
      enabled: false